import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { createHash } from "crypto";
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL, KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.NEXT_SUPABASE_SERVICE_ROLE_KEY;
const POKEMON_API_KEY=process.env.POKEMON_API_KEY;
function admin(){return SUPABASE_URL&&KEY?createClient(SUPABASE_URL,KEY,{auth:{autoRefreshToken:false,persistSession:false}}):null}
function norm(v:string){return String(v||"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function cardLocalNumber(v:string){const first=String(v||"").split("/")[0].replace(/^0+/,"");return first||"0"}
async function resolveImage(a:any,p:any){if(!p||p.image_url||!p.card_name||!p.card_number)return p;const targetName=norm(p.card_name),targetSet=norm(p.card_set||""),number=cardLocalNumber(p.card_number);try{let image:string|null=null;if(POKEMON_API_KEY){const q=`number:${number}* name:${String(p.card_name).split(/\s+/)[0]}*`;const endpoint=new globalThis.URL("https://api.pokemontcg.io/v2/cards");endpoint.searchParams.set("q",q);endpoint.searchParams.set("pageSize","100");const r=await fetch(endpoint.toString(),{headers:{"X-Api-Key":POKEMON_API_KEY,Accept:"application/json"},next:{revalidate:86400}});if(r.ok){const j=await r.json();const cards=Array.isArray(j.data)?j.data:[];const exact=cards.find((c:any)=>norm(c.name)===targetName&&String(c.number||"").replace(/^0+/,"")===number&&(!targetSet||norm(c.set?.name||"")===targetSet))||cards.find((c:any)=>norm(c.name)===targetName&&String(c.number||"").replace(/^0+/,"")===number);image=exact?.images?.large||exact?.images?.small||null;}}if(!image){const endpoint=new globalThis.URL("https://api.tcgdex.net/v2/en/cards");endpoint.searchParams.set("name",`eq:${p.card_name}`);endpoint.searchParams.set("localId",`eq:${number}`);const r=await fetch(endpoint.toString(),{next:{revalidate:86400}});if(r.ok){const cards=await r.json();if(Array.isArray(cards)){for(const c of cards.slice(0,12)){try{const detail=await fetch(`https://api.tcgdex.net/v2/en/cards/${encodeURIComponent(c.id)}`,{next:{revalidate:86400}}).then(x=>x.ok?x.json():null);if(detail&&norm(detail.name)===targetName&&(!targetSet||norm(detail.set?.name||"")===targetSet)){image=detail.image?`${detail.image}/high.webp`:null;break;}}catch{}}}}}if(image){await a.from("welcome_rip_prizes").update({image_url:image}).eq("id",p.prize_id||p.id);return{...p,image_url:image};}}catch(e){console.error("Welcome Rip card image lookup failed",e)}return p;}
async function ctx(r:Request){const a=admin();if(!a)return{a:null,u:null};const h=r.headers.get("authorization")||"";const t=h.startsWith("Bearer ")?h.slice(7):"";if(!t)return{a,u:null};const {data}=await a.auth.getUser(t);return{a,u:data.user||null}}
async function claimInfo(a:any,id:string){const {data:c}=await a.from("welcome_rip_claims").select("id,prize_id,claimed_at,decision,decided_at,collection_id,pullshield_credit_granted,shipping_status,shipped_at").eq("user_id",id).maybeSingle();if(!c)return{claim:null,prize:null};const {data:p}=await a.from("welcome_rip_prizes").select("*").eq("id",c.prize_id).maybeSingle();return{claim:c,prize:p?await resolveImage(a,{...p,claimed_at:c.claimed_at}):null};}
async function info(a:any,id:string){const [{data:h},{count:r}]=await Promise.all([a.from("welcome_rip_households").select("user_id").eq("user_id",id).maybeSingle(),a.from("welcome_rip_prizes").select("id",{count:"exact",head:true}).is("claimed_by",null)]);return{addressVerified:!!h,remaining:r||0}}
export async function GET(r:Request){const{a,u}=await ctx(r);if(!a)return NextResponse.json({error:"Welcome Rip unavailable."},{status:503});if(!u)return NextResponse.json({error:"Authentication required."},{status:401});const [{data:s},ci,i]=await Promise.all([a.from("welcome_rip_settings").select("launch_at,active").eq("singleton",true).maybeSingle(),claimInfo(a,u.id),info(a,u.id)]);const eligible=!!(s?.active&&u.email_confirmed_at&&i.addressVerified&&(i.remaining>0||ci.prize));return NextResponse.json({active:!!s?.active,confirmed:!!u.email_confirmed_at,eligible,alreadyClaimed:!!ci.prize,prize:ci.prize,decision:ci.claim?.decision||null,pullshieldCreditGranted:!!ci.claim?.pullshield_credit_granted,...i})}
export async function POST(r:Request){const{a,u}=await ctx(r);if(!a)return NextResponse.json({error:"Welcome Rip unavailable."},{status:503});if(!u)return NextResponse.json({error:"Authentication required."},{status:401});let body:any={};try{body=await r.json()}catch{}
if(body?.decision==="accept"||body?.decision==="decline"){const ci=await claimInfo(a,u.id);if(!ci.claim||!ci.prize)return NextResponse.json({error:"Open your Welcome Rip first."},{status:409});if(ci.claim.decision!=="pending")return NextResponse.json({error:"You already made your Welcome Rip choice."},{status:409});if(body.decision==="accept"){const cardId=`welcome-rip:${ci.prize.id}`;const {data:added,error:addError}=await a.from("collections").insert({user_id:u.id,card_id:cardId,card_name:ci.prize.card_name||ci.prize.display_name,card_set:ci.prize.card_set,card_number:ci.prize.card_number,language:"English",quantity_owned:1,current_market_value:ci.prize.value_max_cents?Number(ci.prize.value_max_cents)/100:null,date_acquired:new Date().toISOString().slice(0,10),storage_location:"Pull Theory Welcome Rip",personal_notes:"Won from the Pull Theory Welcome Rip.",image_url:ci.prize.image_url}).select("id").single();if(addError)return NextResponse.json({error:"We couldn't add that card to your collection."},{status:500});await a.from("welcome_rip_claims").update({decision:"accepted",decided_at:new Date().toISOString(),collection_id:added.id,shipping_status:"awaiting_shipment"}).eq("id",ci.claim.id).eq("decision","pending");return NextResponse.json({ok:true,decision:"accepted",collectionId:added.id});}
const {data:m,error:me}=await a.from("memberships").select("authentication_credits").eq("user_id",u.id).maybeSingle();if(me)return NextResponse.json({error:"We couldn't issue your PullShield credit."},{status:500});const credits=Math.max(0,Number(m?.authentication_credits||0));if(m){const {error}=await a.from("memberships").update({authentication_credits:credits+1,updated_at:new Date().toISOString()}).eq("user_id",u.id);if(error)return NextResponse.json({error:"We couldn't issue your PullShield credit."},{status:500});}else{const {error}=await a.from("memberships").insert({user_id:u.id,plan:"collector",status:"active",authentication_credits:1});if(error)return NextResponse.json({error:"We couldn't issue your PullShield credit."},{status:500});}await a.from("welcome_rip_claims").update({decision:"declined",decided_at:new Date().toISOString(),pullshield_credit_granted:true,shipping_status:"not_applicable"}).eq("id",ci.claim.id).eq("decision","pending");return NextResponse.json({ok:true,decision:"declined",pullshieldCreditGranted:true});}
if(body?.address){const x=body.address;const vals=["shippingName","address1","city","region","postalCode","country"];if(vals.some(k=>!String(x[k]||"").trim()))return NextResponse.json({error:"Complete your shipping address first."},{status:400});const addr=[x.address1,x.address2,x.city,x.region,x.postalCode,x.country].map((v:any)=>String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"")).join("|");const hash=createHash("sha256").update(addr).digest("hex");const {error}=await a.from("welcome_rip_households").insert({user_id:u.id,address_hash:hash,shipping_name:String(x.shippingName).trim(),address_line1:String(x.address1).trim(),address_line2:String(x.address2||"").trim()||null,city:String(x.city).trim(),region:String(x.region).trim(),postal_code:String(x.postalCode).trim(),country:String(x.country).trim().toUpperCase()});if(error){if(error.code==="23505")return NextResponse.json({error:"A Welcome Rip has already been registered for this household."},{status:409});return NextResponse.json({error:"We couldn't save that address."},{status:500});}return NextResponse.json({ok:true,addressVerified:true});}
const {data,error}=await a.rpc("claim_welcome_rip",{target_user_id:u.id});if(error)return NextResponse.json({error:"We couldn't open your Welcome Rip."},{status:500});let p=Array.isArray(data)?data[0]:data;if(!p)return NextResponse.json({error:"Confirm your email and shipping address before opening your Welcome Rip."},{status:403});p=await resolveImage(a,p);const i=await info(a,u.id);return NextResponse.json({ok:true,prize:p,decision:"pending",...i});}