"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {getCurrentAccessToken} from "../../lib/supabase";

type Data={code:string|null;stats:{verified:number;paidMembers:number;earnedCents:number;paidCents:number;owedCents:number};referrals:Array<{id:number;status:string;createdAt:string}>};
const money=(c:number)=>`$${(c/100).toFixed(2)}`;
export default function AmbassadorDashboard(){const [data,setData]=useState<Data|null>(null),[code,setCode]=useState(""),[msg,setMsg]=useState("");
 async function load(){const t=await getCurrentAccessToken();if(!t){location.href=`/login?returnTo=${encodeURIComponent("/ambassadors/dashboard")}`;return;}const r=await fetch("/api/ambassadors",{headers:{Authorization:`Bearer ${t}`}});const j=await r.json();if(r.ok)setData(j);else setMsg(j.error||"Unable to load dashboard.");}
 useEffect(()=>{void load()},[]);
 async function create(){setMsg("");const t=await getCurrentAccessToken();if(!t)return;const r=await fetch("/api/ambassadors",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({code})});const j=await r.json();if(!r.ok){setMsg(j.error||"Unable to create code.");return;}await load();}
 const link=data?.code?`https://pulltheorytrade.com/signup?ref=${encodeURIComponent(data.code)}`:"";
 return <main className="min-h-screen px-5 py-12 text-white"><div className="mx-auto max-w-5xl"><Link href="/ambassadors" className="text-violet-300">← Ambassador Program</Link><h1 className="mt-5 text-4xl font-bold">Ambassador Dashboard</h1><p className="mt-3 text-zinc-400">Earn $0.50 for each verified referral and a $5.00 bonus when they become a paid member.</p>{!data?<p className="mt-8">Loading...</p>:!data.code?<section className="mt-8 rounded-3xl border border-white/10 bg-white/5 p-6"><h2 className="text-2xl font-semibold">Create your referral code</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={24} placeholder="YOURCODE" className="flex-1 rounded-xl border border-white/10 bg-black/40 px-4 py-3"/><button onClick={create} className="rounded-xl bg-violet-600 px-5 py-3 font-bold">Create code</button></div></section>:<><section className="mt-8 rounded-3xl border border-violet-400/30 bg-violet-500/10 p-6"><p className="text-sm text-zinc-300">Your code</p><p className="mt-1 text-3xl font-bold text-amber-300">{data.code}</p><p className="mt-5 break-all rounded-xl bg-black/30 p-3 text-sm">{link}</p><button onClick={()=>navigator.clipboard.writeText(link)} className="mt-3 rounded-xl border border-white/15 px-4 py-2 font-semibold">Copy referral link</button></section><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Verified",String(data.stats.verified)],["Paid members",String(data.stats.paidMembers)],["Earned",money(data.stats.earnedCents)],["Paid",money(data.stats.paidCents)],["Amount owed",money(data.stats.owedCents)]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-black/30 p-4"><p className="text-xs text-zinc-400">{a}</p><p className="mt-2 text-2xl font-bold">{b}</p></div>)}</div><section className="mt-6 rounded-3xl border border-white/10 bg-black/30 p-6"><h2 className="text-xl font-semibold">Recent referrals</h2>{data.referrals.length===0?<p className="mt-4 text-zinc-400">No referrals yet. Share your link to get started.</p>:<div className="mt-4 space-y-2">{data.referrals.slice(0,50).map(r=><div key={r.id} className="flex justify-between rounded-xl border border-white/10 p-3"><span>Referral #{r.id}</span><span className="capitalize text-violet-200">{r.status.replace("_"," ")}</span></div>)}</div>}</section></>}{msg&&<p className="mt-5 rounded-xl bg-rose-500/10 p-3 text-rose-200">{msg}</p>}</div></main>}
