"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import OfferModal from "../../components/OfferModal";
import {getSupabaseClient} from "../../lib/supabase";
import {cardFinishLabel,decodeCardDetails} from "../../lib/cardDetails";
import BuyNowButton from "../../components/BuyNowButton";

type Listing={id:number;name:string;offeredCard:string;desiredCard:string;notes?:string;user_id?:string|null;photoUrls?:string[];listingType?:"trade"|"sell"|"trade_or_sell";salePriceCents?:number|null};
const giveaway=["Pikachu — PSA 10","Swablu — PSA 9","Giovanni's Exile (Full Art) — PSA 9","Iono's Kilowattrel — PSA 8","Team Rocket's Orbeetle — PSA 9"];
export default function BrowseMarketplacePage(){
 const[listings,setListings]=useState<Listing[]>([]),[loading,setLoading]=useState(true),[userId,setUserId]=useState<string|null>(null),[query,setQuery]=useState(""),[selected,setSelected]=useState<Listing|null>(null);
 async function load(){setLoading(true);try{const r=await fetch("/api/trades?is_listing=true&pageSize=100");const j=await r.json();setListings(r.ok?j.items??[]:[])}finally{setLoading(false)}}
 useEffect(()=>{void load();const s=getSupabaseClient();void s?.auth.getSession().then(({data}:any)=>setUserId(data.session?.user.id??null))},[]);
 const visible=listings.filter(l=>`${l.offeredCard} ${l.desiredCard} ${l.name} ${l.notes??""}`.toLowerCase().includes(query.trim().toLowerCase()));
 return <main className="min-h-screen bg-[#050506] px-4 py-8 text-white sm:px-6 sm:py-12"><div className="mx-auto max-w-7xl">
  <section className="mb-8 rounded-[2rem] border border-amber-300/30 bg-amber-300/[.05] p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-amber-300">🎁 Membership Giveaway</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Win all 5 graded Pokémon cards.</h1><p className="mt-3 max-w-2xl text-zinc-300">One winner receives the complete five-card bundle. Winner selected December 20, 2026.</p></div><Link href={userId?"/pricing":"/signup?returnTo=/pricing"} className="rounded-2xl bg-amber-300 px-6 py-4 text-center font-black text-black">{userId?"VIEW MEMBERSHIP":"JOIN MEMBERSHIP"}</Link></div><div className="mt-6 rounded-3xl bg-transparent p-2"><img src="/giveaway/cards-transparent.webp" alt="Pikachu, Swablu, Giovanni's Exile, Iono's Kilowattrel, and Team Rocket's Orbeetle graded Pokémon cards" className="mx-auto block w-full max-w-5xl object-contain" /></div><div className="mt-4 grid gap-2 text-center text-sm font-bold text-zinc-200 sm:grid-cols-5">{giveaway.map(x=><div key={x}>{x}</div>)}</div></section>
  {!userId&&<section className="mb-8 flex flex-col gap-3 rounded-3xl border border-violet-400/20 bg-violet-500/[.06] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">Browse the marketplace without an account.</p><p className="text-sm text-zinc-400">Sign up when you are ready to buy, sell, trade, or make an offer.</p></div><Link href="/signup" className="rounded-xl bg-violet-600 px-5 py-3 text-center font-bold">Sign up free</Link></section>}
  <section className="rounded-[2rem] border border-violet-400/20 bg-white/[.035] p-7 sm:p-10"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.24em] text-amber-300">Marketplace</p><h2 className="mt-2 text-4xl font-black sm:text-5xl">Buy, Sell, or Trade</h2><p className="mt-3 max-w-2xl text-zinc-300">Browse active Pokémon card listings. PullShield protects transactions by verifying cards before completion.</p></div><div className="flex gap-3"><Link href="/search" className="rounded-xl border border-white/15 px-4 py-3 font-semibold">Find a Card</Link><Link href={userId?"/marketplace/list":"/signup"} className="rounded-xl bg-violet-600 px-4 py-3 font-bold">＋ List a Card</Link></div></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cards, sets, collectors, or wanted cards" className="mt-7 w-full rounded-2xl border border-white/10 bg-black/30 px-5 py-4 outline-none placeholder:text-zinc-600"/></section>
  <div className="mt-8 flex items-center justify-between"><h2 className="text-2xl font-bold">Active listings</h2><button onClick={()=>void load()} className="text-sm font-semibold text-violet-300">Refresh</button></div>
  <section className="mt-5 grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-3 xl:grid-cols-4">{loading?<p className="col-span-full text-zinc-400">Loading marketplace listings...</p>:visible.length?visible.map(l=>{const d=decodeCardDetails(l.notes);const buy=(l.listingType==="sell"||l.listingType==="trade_or_sell")&&!!l.salePriceCents;const trade=l.listingType!=="sell";return <article key={l.id} className="flex flex-col rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold text-emerald-300">{l.listingType==="sell"?"For sale":l.listingType==="trade_or_sell"?"Trade or sell":"Available for trade"}</span><span className="text-xs text-zinc-500">#{l.id}</span></div>{l.photoUrls?.[0]&&<img src={l.photoUrls[0]} alt={`Front of ${l.offeredCard}`} className="mt-4 aspect-[2.5/3.5] w-full rounded-2xl bg-black/20 object-contain"/>}<h3 className="mt-4 text-xl font-bold">{l.offeredCard}</h3>{buy&&<p className="mt-2 font-bold text-emerald-200">{(l.salePriceCents!/100).toLocaleString("en-US",{style:"currency",currency:"USD"})}</p>}<p className="mt-2 text-sm text-zinc-400">Listed by {l.name}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs">{d.finish&&<div className="rounded-xl bg-black/25 p-2">Finish: {cardFinishLabel(d.finish)}</div>}{d.condition&&<div className="rounded-xl bg-black/25 p-2">Condition: {d.condition}</div>}{d.grade&&<div className="rounded-xl bg-black/25 p-2">Grade: {d.gradingCompany||""} {d.grade}</div>}</div><div className="mt-auto grid gap-2 pt-5"><Link href={`/marketplace/${l.id}`} className="rounded-xl border border-white/15 px-4 py-3 text-center text-sm font-semibold">View details</Link>{trade&&<button onClick={()=>userId?setSelected(l):window.location.assign(`/signup?returnTo=${encodeURIComponent(`/marketplace/${l.id}`)}`)} className="rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold">{userId?"Offer trade":"Sign up to offer"}</button>}{buy&&<BuyNowButton listingId={l.id} priceCents={l.salePriceCents!} className="w-full"/>}</div></article>}) : <div className="col-span-full rounded-3xl border border-dashed border-white/15 p-10 text-center text-zinc-400">No listings match your search.</div>}</section>
 </div>{selected&&<OfferModal listing={selected} onClose={()=>setSelected(null)} onSubmitted={()=>{setSelected(null);void load()}}/>}</main>}
export function PublicLanding(){return <BrowseMarketplacePage/>}
