create table if not exists public.referral_codes (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists referral_codes_code_lower_idx on public.referral_codes (lower(code));
create unique index if not exists referral_codes_owner_idx on public.referral_codes (owner_user_id);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referral_code_id bigint not null references public.referral_codes(id) on delete restrict,
  referred_user_id uuid not null references auth.users(id) on delete cascade,
  referred_email text not null,
  status text not null default 'pending' check (status in ('pending','confirmed','paid_member','rejected')),
  signup_reward_cents integer not null default 50,
  paid_member_bonus_cents integer not null default 500,
  signup_reward_paid boolean not null default false,
  paid_member_bonus_paid boolean not null default false,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  paid_member_at timestamptz,
  unique (referred_user_id)
);
create index if not exists referrals_code_idx on public.referrals (referral_code_id, created_at desc);

alter table public.referral_codes enable row level security;
alter table public.referrals enable row level security;

create policy "owners can read their referral code" on public.referral_codes for select using (auth.uid() = owner_user_id);
create policy "owners can read their referral results" on public.referrals for select using (exists (select 1 from public.referral_codes rc where rc.id = referral_code_id and rc.owner_user_id = auth.uid()));
