create table if not exists public.pullshield_trade_payments (
  id bigint generated by default as identity primary key,
  offer_id bigint not null references public.trades(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null default 'collector',
  amount_cents integer not null default 0,
  status text not null default 'pending',
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (offer_id, user_id)
);

alter table public.pullshield_trade_payments enable row level security;

create policy "Users can view their own PullShield trade payments"
on public.pullshield_trade_payments for select
using (auth.uid() = user_id);
